//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialCountityCalculation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int Id { get; set; }
        public int PartnerTypeId { get; set; }
        public string PartnerName { get; set; }
        public string DirectorSurname { get; set; }
        public string DirectorName { get; set; }
        public string DirectorPatronym { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AdresIndex { get; set; }
        public int RegionId { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
        public int HouseNumber { get; set; }
        public string IndividualTaxNumber { get; set; }
        public int Rating { get; set; }
    
        public virtual Cities Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
        public virtual PartnersTypes PartnersTypes { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual Streets Streets { get; set; }
    }
}
